# Generated by Django 4.2.3 on 2023-07-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=50)),
                ('operation_airlines', models.CharField(max_length=50)),
                ('departure_city', models.CharField(max_length=50)),
                ('arrival_city', models.CharField(max_length=50)),
                ('date_of_departure', models.DateTimeField(verbose_name='date published')),
                ('estimated_time_of_departure', models.DateTimeField(verbose_name='date_published')),
            ],
        ),
    ]
