# Generated by Django 4.2.3 on 2023-07-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_passenger_alter_flight_date_of_departure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='date_of_departure',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='estimated_time_of_departure',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='operation_airlines',
            field=models.CharField(choices=[('THY', 'TÜRK HAVAYOLLARI'), ('PHT', 'PEGASUS HAVA TAŞIMACILIĞI'), ('AJH', 'ATLAS JET HAVACILIK'), ('OİT', 'ONUR AİR TAŞIMACILIK')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rezervation',
            name='passenger',
            field=models.ManyToManyField(related_name='passengers', to='flight.passenger'),
        ),
    ]
