# Generated by Django 4.2.3 on 2023-07-20 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0004_rezervation_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rezervation',
            name='name',
        ),
    ]
