# Generated by Django 4.2.3 on 2023-07-23 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0006_alter_flight_options_alter_passenger_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ('flight_number',), 'verbose_name_plural': 'Uçuş Bilgileri'},
        ),
        migrations.AlterModelOptions(
            name='passenger',
            options={'ordering': ('firstName',), 'verbose_name_plural': 'Yolcu Bilgileri'},
        ),
    ]
